# version: "3"
# # this file uses prebuilt image in dockerhub
# services:
#   jekyll:
#     image: amirpourmand/al-folio
#     ports:
#       - 8080:8080
#     volumes:
#       - .:/srv/jekyll
#       - bundle-cache:/usr/local/bundle

version: '3'

services:
  jekyll:
    image: amirpourmand/al-folio
    ports:
      - "8080:8080"
    volumes:
      - .:/srv/jekyll
      - bundle-cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=production
    command: bundle exec jekyll serve --host=0.0.0.0 --port=8080 --livereload --force_polling --watch
    user: root  # 以 root 用户运行，确保对文件的写权限

volumes:
  bundle-cache:
